from django.urls import path, include
from shortener import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r"api/links", views.LinkViewSet, basename="link")

urlpatterns = [
    # --- DRF Endpoints (Generated by Router) ---
    path("", include(router.urls)),  # Include the ViewSet URLs
    # Django view for handling the actual redirection
    # The name 'redirect_short_url' is used by the serializer's get_short_url method
    path("<str:short_code>/", views.redirect_view, name="redirect_short_url"),
]
