from django.urls import path, include
from shortener import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r"api/links", views.LinkViewSet, basename="link")

urlpatterns = [
    # DRF Endpoints (Generated by Router)
    path("", include(router.urls)),  # Include the ViewSet URLs
    # Visits list for a specific link
    path(
        "api/links/<str:link_short_code>/visits/",
        views.LinkVisitListView.as_view(),
        name="link-visit-list",
    ),
    # Django view for handling redirection
    path("<str:short_code>/", views.redirect_view, name="redirect-short-url"),
]
