# Generated by Django 5.2 on 2025-04-30 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='shortener.link')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
