# Generated by Django 5.2 on 2025-04-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, help_text='Denormalized count of visits.'),
        ),
    ]
